pipeline:
  identifier: Build_Calculator_1700214555237
  name: Build Calculator
  orgIdentifier: default
  projectIdentifier: calculator
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Calculator
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: dockerfile
                  identifier: dockerfile
                  spec:
                    connectorRef: dockerregistry
                    image: cal
                    shell: Sh
                    command: |-
                      docker build -t cal .
                      docker run -d -p 3000:3000 --name calculator cal
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
